services:

  php:
    build: 
      context: ./backend
    container_name: symfony-php
    volumes:
      - ./backend:/var/www
    working_dir: /var/www

  nginx: 
    image: nginx:stable-alpine
    container_name: symfony-nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  ui: 
    build: 
      context: ./frontend
    container_name: react
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"